version: '2'

services:
  postgres:
    build:
      context: postgres/
    ports:
    - "5432:5432"
    volumes:
      - ./postgres/init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres